using System;
using System.Drawing;
using System.Windows.Forms;

namespace Lab11
{
    public partial class Form4 : Form
    {
        public Form4()
        {
            InitializeComponent();
        }

        /*
         * Event: KeyDemo_KeyPress (Form's KeyPress event)
         * Objective: Display the character generated by the keystroke (e.g., 'H', '$').
         */
        private void KeyDemo_KeyPress(object sender, KeyPressEventArgs e)
        {
            // The e.KeyChar provides the character that was typed.
            charLabel.Text = "Key pressed: " + e.KeyChar;
        }

        /*
         * Event: KeyDemo_KeyDown (Form's KeyDown event)
         * Objective: Display detailed system information about the key (Alt, Shift, Ctrl, KeyCode, KeyData, KeyValue).
         */
        private void KeyDemo_KeyDown(object sender, KeyEventArgs e)
        {
            // Environment.NewLine is used for creating clean, platform-independent line breaks.
            keyInfoLabel.Text =
                "Alt: " + (e.Alt ? "Yes" : "No") + Environment.NewLine +
                "Shift: " + (e.Shift ? "Yes" : "No") + Environment.NewLine +
                "Ctrl: " + (e.Control ? "Yes" : "No") + Environment.NewLine +
                "KeyCode: " + e.KeyCode + Environment.NewLine +
                "KeyData: " + e.KeyData + Environment.NewLine +
                "KeyValue: " + e.KeyValue;
        }

        /*
         * Event: KeyDemo_KeyUp (Form's KeyUp event)
         * Objective: Clear the labels when the key is released, resetting the display.
         */
        private void KeyDemo_KeyUp(object sender, KeyEventArgs e)
        {
            // Clear both labels to reset the display
            charLabel.Text = string.Empty;
            keyInfoLabel.Text = string.Empty;
        }
    }
}